export const MOCK_ANNOUNCEMENTS = [
    {
        id: '1',
        title: 'Midterm Exam Schedule',
        content: 'The midterm exams for the Fall semester will begin on January 15th. Please check your department boards for specific timings.',
        author: 'Academic Office',
        date: '2025-12-28',
        isGlobal: true,
        authorId: 'admin-01',
        comments: [
            { id: 'c1', user: 'Med Omar', content: 'Will it be online or on-campus?', date: '2025-12-28' },
        ],
    },
    {
        id: '2',
        title: 'New Library Opening Hours',
        content: 'Starting next week, the central library will be open 24/7 to support students during the exam period.',
        author: 'Library Services',
        date: '2025-12-27',
        isGlobal: true,
        authorId: 'admin-02',
        comments: [],
    },
    {
        id: '3',
        title: 'Software Engineering Project Phase 1',
        content: 'Please submit your group members and project topics by Friday. This is mandatory for CS 3rd Year students.',
        author: 'Mohamed Farah (Delegate)',
        date: '2025-12-29',
        isGlobal: false,
        department: 'Computer Science',
        level: '3rd Year',
        authorId: '20230999',
        comments: [],
    },
    {
        id: '4',
        title: 'Advanced Algorithms Quiz',
        content: 'There will be a surprise-ish quiz this Thursday covering Graph theory. Be prepared.',
        author: 'Dr. Aisha Ahmed',
        date: '2025-12-30',
        isGlobal: false,
        department: 'Computer Science',
        level: '3rd Year',
        authorId: 'TCH-007',
        comments: [],
    },
];

export const MOCK_STUDENTS = [
    { id: '20230889', name: 'Abdifatah Ismal', department: 'Computer Science', level: '3rd Year', attendance: 0.92, grade: '17/20' },
    { id: '20230999', name: 'Mohamed Farah', department: 'Computer Science', level: '3rd Year', attendance: 0.98, grade: '18/20' },
    { id: '20230442', name: 'Med Omar', department: 'Computer Science', level: '3rd Year', attendance: 0.85, grade: '16/20' },
    { id: '20230115', name: 'Fatima Ali', department: 'Computer Science', level: '3rd Year', attendance: 0.95, grade: '18/20' },
    { id: '20230773', name: 'Hassan Mohamed', department: 'Computer Science', level: '3rd Year', attendance: 0.70, grade: '15/20' },
];

export const MOCK_RESOURCES = [
    {
        id: 'r1',
        title: 'Lecture 01: Introduction to React Native',
        type: 'pdf',
        size: '2.4 MB',
        category: 'Lecture Notes',
        date: '2025-12-01'
    },
    {
        id: 'r2',
        title: 'Project Requirements Template',
        type: 'docx',
        size: '1.1 MB',
        category: 'Assignments',
        date: '2025-12-05'
    },
    {
        id: 'r3',
        title: 'Graph Theory Recap Slides',
        type: 'pptx',
        size: '5.8 MB',
        category: 'Lecture Notes',
        date: '2025-12-15'
    },
    {
        id: 'r4',
        title: 'Midterm Exam Solution Key',
        type: 'pdf',
        size: '1.5 MB',
        category: 'Exams',
        date: '2025-12-20'
    },
];

export const MOCK_GROUPS = [
    {
        id: 'g1',
        name: 'CS Year 3 - Main',
        description: 'General discussion for 3rd year Computer Science students.',
        messages: [
            { id: 'm1', sender: 'Alice', content: 'Did anyone figure out Question 4 on the assignment?', type: 'received' },
            { id: 'm2', sender: 'Bob', content: 'Yeah, I used Dijkstra algorithm.', type: 'received' },
            { id: 'm3', sender: 'You', content: 'I still haven\'t started lol', type: 'sent' },
        ],
    },
    {
        id: 'g2',
        name: 'Project Group 7',
        description: 'Design Project - Team 7',
        messages: [],
    },
    {
        id: 'g3',
        name: 'SE Department Faculty',
        description: 'Private group for SE Department Staff.',
        messages: [],
    },
];

export const MOCK_TIMETABLE = {
    Sunday: [
        { id: 't1', subject: 'Software Engineering', time: '09:00 - 11:00', room: 'Hall A' },
        { id: 't2', subject: 'Database Systems', time: '13:00 - 15:00', room: 'Room 302' },
    ],
    Monday: [
        { id: 't3', subject: 'Web Development', time: '10:00 - 12:00', room: 'Lab 1' },
        { id: 't8', subject: 'AI Foundations', time: '14:00 - 16:00', room: 'Room 405' },
    ],
    Tuesday: [
        { id: 't4', subject: 'Cloud Computing', time: '09:00 - 11:00', room: 'Hall B' },
        { id: 't5', subject: 'Machine Learning', time: '14:00 - 16:00', room: 'Lab 2' },
    ],
    Wednesday: [
        { id: 't6', subject: 'Network Security', time: '11:00 - 13:00', room: 'Room 101' },
        { id: 't9', subject: 'Mobile App Dev', time: '15:00 - 17:00', room: 'Lab 3' },
    ],
    Thursday: [
        { id: 't7', subject: 'Professional Ethics', time: '09:00 - 11:00', room: 'Hall C' },
    ],
};

export const MOCK_GRADES = [
    {
        id: 's1', semester: 'Semester 5', gpa: '3.8', courses: [
            { name: 'Operating Systems', grade: '18/20', credits: 4 },
            { name: 'Computer Networks', grade: '17/20', credits: 3 },
            { name: 'Human Computer Interaction', grade: '16/20', credits: 3 },
        ]
    },
    {
        id: 's2', semester: 'Semester 4', gpa: '3.6', courses: [
            { name: 'Data Structures', grade: '18/20', credits: 4 },
            { name: 'Discrete Math', grade: '15/20', credits: 3 },
            { name: 'OOP', grade: '18/20', credits: 4 },
        ]
    },
];

export const MOCK_EXAM_CALENDAR = [
    {
        id: 'e1',
        course: 'Operating Systems',
        examType: 'Midterm',
        date: '2025-01-15',
        time: '09:00 - 11:00',
        room: 'Hall A',
        duration: '2 hours',
        status: 'upcoming',
    },
    {
        id: 'e2',
        course: 'Computer Networks',
        examType: 'Midterm',
        date: '2025-01-17',
        time: '14:00 - 16:00',
        room: 'Hall B',
        duration: '2 hours',
        status: 'upcoming',
    },
    {
        id: 'e3',
        course: 'Database Systems',
        examType: 'Final',
        date: '2025-02-10',
        time: '09:00 - 12:00',
        room: 'Hall C',
        duration: '3 hours',
        status: 'upcoming',
    },
    {
        id: 'e4',
        course: 'Web Development',
        examType: 'Final',
        date: '2025-02-12',
        time: '13:00 - 16:00',
        room: 'Lab 1',
        duration: '3 hours',
        status: 'upcoming',
    },
    {
        id: 'e5',
        course: 'Data Structures',
        examType: 'Midterm',
        date: '2024-12-10',
        time: '10:00 - 12:00',
        room: 'Hall A',
        duration: '2 hours',
        status: 'completed',
    },
];

export const MOCK_EXAM_RESULTS = [
    {
        id: 'er1',
        course: 'Data Structures',
        examType: 'Midterm',
        date: '2024-12-10',
        score: 17,
        maxScore: 20,
        grade: '17/20',
        status: 'passed',
    },
    {
        id: 'er2',
        course: 'Discrete Math',
        examType: 'Final',
        date: '2024-11-20',
        score: 18.4,
        maxScore: 20,
        grade: '18.4/20',
        status: 'passed',
    },
    {
        id: 'er3',
        course: 'OOP',
        examType: 'Final',
        date: '2024-11-25',
        score: 17.6,
        maxScore: 20,
        grade: '17.6/20',
        status: 'passed',
    },
    {
        id: 'er4',
        course: 'Operating Systems',
        examType: 'Quiz 1',
        date: '2024-10-15',
        score: 15.6,
        maxScore: 20,
        grade: '15.6/20',
        status: 'passed',
    },
];

export const MOCK_ACADEMIC_STATUS = {
    studentId: '20230889',
    name: 'Abdifatah Ismal',
    department: 'Computer Science',
    level: '3rd Year',
    currentSemester: 'Semester 5',
    totalCredits: 120,
    completedCredits: 96,
    gpa: 3.8,
    cgpa: 3.7,
    status: 'Active',
    enrollmentDate: '2022-09-01',
    expectedGraduation: '2026-06-30',
    academicStanding: 'Good Standing',
    warnings: 0,
    probation: false,
};

export const MOCK_STUDENT_ATTENDANCE = [
    {
        courseId: 'CS301',
        courseCode: 'CS301',
        courseName: 'Operating Systems',
        totalClasses: 30,
        present: 28,
        absent: 2,
        attendanceRate: 93.3,
        instructor: 'Dr. Aisha Ahmed',
    },
    {
        courseId: 'CS302',
        courseCode: 'CS302',
        courseName: 'Computer Networks',
        totalClasses: 20,
        present: 19,
        absent: 1,
        attendanceRate: 95.0,
        instructor: 'Dr. Hassan Mohamed',
    },
    {
        courseId: 'CS303',
        courseCode: 'CS303',
        courseName: 'Database Systems',
        totalClasses: 28,
        present: 26,
        absent: 2,
        attendanceRate: 92.9,
        instructor: 'Dr. Fatima Ali',
    },
    {
        courseId: 'CS304',
        courseCode: 'CS304',
        courseName: 'Web Development',
        totalClasses: 18,
        present: 17,
        absent: 1,
        attendanceRate: 94.4,
        instructor: 'Dr. Aisha Ahmed',
    },
    {
        courseId: 'CS305',
        courseCode: 'CS305',
        courseName: 'Human Computer Interaction',
        totalClasses: 22,
        present: 20,
        absent: 2,
        attendanceRate: 90.9,
        instructor: 'Dr. Mohamed Farah',
    },
    {
        courseId: 'CS306',
        courseCode: 'CS306',
        courseName: 'Cloud Computing',
        totalClasses: 24,
        present: 23,
        absent: 1,
        attendanceRate: 95.8,
        instructor: 'Dr. Hassan Mohamed',
    },
];

export const MOCK_COURSES = [
    {
        id: 'CS301',
        code: 'CS301',
        name: 'Operating Systems',
        credits: 4,
        instructor: 'Dr. Aisha Ahmed',
        instructorId: 'TCH-007',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Monday', time: '09:00 - 11:00', room: 'Hall A' },
            { day: 'Wednesday', time: '09:00 - 11:00', room: 'Hall A' },
        ],
        enrolled: true,
        grade: '18/20',
        status: 'In Progress',
        description: 'Introduction to operating systems concepts, process management, memory management, and file systems.',
        pdfs: [
            { id: 'pdf1', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs301-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf2', name: 'Chapter 1: Introduction to OS', type: 'lecture', url: 'https://example.com/cs301-ch1.pdf', date: '2025-01-10' },
            { id: 'pdf3', name: 'Midterm Assessment', type: 'assessment', url: 'https://example.com/cs301-midterm.pdf', date: '2025-01-15' },
            { id: 'pdf4', name: 'Assignment 1 - Process Scheduling', type: 'assignment', url: 'https://example.com/cs301-assign1.pdf', date: '2025-01-20' },
        ],
    },
    {
        id: 'CS302',
        code: 'CS302',
        name: 'Computer Networks',
        credits: 3,
        instructor: 'Dr. Hassan Mohamed',
        instructorId: 'TCH-008',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Monday', time: '13:00 - 15:00', room: 'Room 302' },
        ],
        enrolled: true,
        grade: '17/20',
        status: 'In Progress',
        description: 'Fundamentals of computer networking, protocols, and network architecture.',
        pdfs: [
            { id: 'pdf5', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs302-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf6', name: 'TCP/IP Protocol Suite', type: 'lecture', url: 'https://example.com/cs302-tcpip.pdf', date: '2025-01-12' },
            { id: 'pdf7', name: 'Network Security Assessment', type: 'assessment', url: 'https://example.com/cs302-assessment.pdf', date: '2025-01-18' },
        ],
    },
    {
        id: 'CS303',
        code: 'CS303',
        name: 'Database Systems',
        credits: 4,
        instructor: 'Dr. Fatima Ali',
        instructorId: 'TCH-009',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Tuesday', time: '10:00 - 12:00', room: 'Lab 1' },
            { day: 'Thursday', time: '10:00 - 12:00', room: 'Lab 1' },
        ],
        enrolled: true,
        grade: null,
        status: 'In Progress',
        description: 'Database design, SQL, normalization, and database management systems.',
        pdfs: [
            { id: 'pdf8', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs303-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf9', name: 'SQL Basics Guide', type: 'lecture', url: 'https://example.com/cs303-sql.pdf', date: '2025-01-14' },
            { id: 'pdf10', name: 'Database Design Project', type: 'assignment', url: 'https://example.com/cs303-project.pdf', date: '2025-01-25' },
        ],
    },
    {
        id: 'CS304',
        code: 'CS304',
        name: 'Web Development',
        credits: 3,
        instructor: 'Dr. Aisha Ahmed',
        instructorId: 'TCH-007',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Tuesday', time: '14:00 - 16:00', room: 'Room 405' },
        ],
        enrolled: true,
        grade: null,
        status: 'In Progress',
        description: 'Modern web development with React, Node.js, and full-stack applications.',
        pdfs: [
            { id: 'pdf11', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs304-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf12', name: 'React Fundamentals', type: 'lecture', url: 'https://example.com/cs304-react.pdf', date: '2025-01-16' },
        ],
    },
    {
        id: 'CS305',
        code: 'CS305',
        name: 'Human Computer Interaction',
        credits: 3,
        instructor: 'Dr. Mohamed Farah',
        instructorId: 'TCH-010',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Wednesday', time: '14:00 - 16:00', room: 'Lab 2' },
        ],
        enrolled: true,
        grade: '16/20',
        status: 'In Progress',
        description: 'User interface design, usability principles, and interaction design patterns.',
        pdfs: [
            { id: 'pdf13', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs305-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf14', name: 'UI/UX Design Principles', type: 'lecture', url: 'https://example.com/cs305-uiux.pdf', date: '2025-01-18' },
        ],
    },
    {
        id: 'CS306',
        code: 'CS306',
        name: 'Cloud Computing',
        credits: 3,
        instructor: 'Dr. Hassan Mohamed',
        instructorId: 'TCH-008',
        department: 'Computer Science',
        level: '3rd Year',
        semester: 'Semester 5',
        schedule: [
            { day: 'Thursday', time: '11:00 - 13:00', room: 'Room 101' },
        ],
        enrolled: true,
        grade: null,
        status: 'In Progress',
        description: 'Cloud infrastructure, services, and deployment strategies.',
        pdfs: [
            { id: 'pdf15', name: 'Course Syllabus', type: 'syllabus', url: 'https://example.com/cs306-syllabus.pdf', date: '2025-01-05' },
            { id: 'pdf16', name: 'AWS Services Overview', type: 'lecture', url: 'https://example.com/cs306-aws.pdf', date: '2025-01-22' },
        ],
    },
    {
        id: 'CS201',
        code: 'CS201',
        name: 'Data Structures',
        credits: 4,
        instructor: 'Dr. Aisha Ahmed',
        instructorId: 'TCH-007',
        department: 'Computer Science',
        level: '2nd Year',
        semester: 'Semester 4',
        schedule: [
            { day: 'Monday', time: '09:00 - 11:00', room: 'Hall B' },
        ],
        enrolled: false,
        grade: '18/20',
        status: 'Completed',
    },
    {
        id: 'CS202',
        code: 'CS202',
        name: 'Object-Oriented Programming',
        credits: 4,
        instructor: 'Dr. Fatima Ali',
        instructorId: 'TCH-009',
        department: 'Computer Science',
        level: '2nd Year',
        semester: 'Semester 4',
        schedule: [
            { day: 'Wednesday', time: '09:00 - 11:00', room: 'Hall C' },
        ],
        enrolled: false,
        grade: '18/20',
        status: 'Completed',
    },
];
